export type MalaysiaFacilitySeed = {
  state: string;
  kind: "hospital" | "clinic";
  name: string;
  slug: string;
  address: string;
  latitude: string;
  longitude: string;
  accent: "emerald" | "blue" | "violet" | "amber";
};

export const malaysiaFacilities: MalaysiaFacilitySeed[] = [
  // Johor
  {
    state: "Johor",
    kind: "hospital",
    name: "Hospital Sultanah Aminah",
    slug: "hospital-sultanah-aminah-johor",
    address: "Jalan Persiaran Abu Bakar Sultan, 80100 Johor Bahru, Johor",
    latitude: "1.4600801",
    longitude: "103.7469025",
    accent: "emerald",
  },
  {
    state: "Johor",
    kind: "hospital",
    name: "Gleneagles Hospital Medini Johor",
    slug: "gleneagles-hospital-medini-johor",
    address: "No. 2, Jalan Medini Utara 4, Medini Iskandar, 79250 Iskandar Puteri, Johor",
    latitude: "1.4260413",
    longitude: "103.6363238",
    accent: "blue",
  },
  {
    state: "Johor",
    kind: "clinic",
    name: "Klinik Kesihatan Mahmoodiah",
    slug: "klinik-kesihatan-mahmoodiah-johor",
    address: "Jalan Mahmoodiah, 80100 Johor Bahru, Johor",
    latitude: "1.4630477",
    longitude: "103.7483141",
    accent: "violet",
  },
  {
    state: "Johor",
    kind: "clinic",
    name: "Klinik Kesihatan Sultan Ismail",
    slug: "klinik-kesihatan-sultan-ismail-johor",
    address: "Taman Mount Austin, 81100 Johor Bahru, Johor",
    latitude: "1.5481209",
    longitude: "103.7895504",
    accent: "amber",
  },

  // Kedah
  {
    state: "Kedah",
    kind: "hospital",
    name: "Hospital Sultanah Bahiyah",
    slug: "hospital-sultanah-bahiyah-kedah",
    address: "KM 6, Jalan Langgar, 05460 Alor Setar, Kedah",
    latitude: "6.1490640",
    longitude: "100.4067648",
    accent: "emerald",
  },
  {
    state: "Kedah",
    kind: "hospital",
    name: "KPJ Kedah Medical Centre",
    slug: "kpj-kedah-medical-centre",
    address: "Pumpong, 05250 Alor Setar, Kedah",
    latitude: "6.1489060",
    longitude: "100.3693877",
    accent: "blue",
  },
  {
    state: "Kedah",
    kind: "clinic",
    name: "Klinik Kesihatan Bandar Alor Setar",
    slug: "klinik-kesihatan-bandar-alor-setar-kedah",
    address: "Jalan Putra, 05100 Alor Setar, Kedah",
    latitude: "6.1413093",
    longitude: "100.3710174",
    accent: "violet",
  },
  {
    state: "Kedah",
    kind: "clinic",
    name: "Klinik Kesihatan Mergong",
    slug: "klinik-kesihatan-mergong-kedah",
    address: "Jalan Lencong Barat, Mergong, 05150 Alor Setar, Kedah",
    latitude: "6.1362032",
    longitude: "100.3423974",
    accent: "amber",
  },

  // Kelantan
  {
    state: "Kelantan",
    kind: "hospital",
    name: "Hospital Raja Perempuan Zainab II",
    slug: "hospital-raja-perempuan-zainab-ii-kelantan",
    address: "Jalan Hospital, 15000 Kota Bharu, Kelantan",
    latitude: "6.1247735",
    longitude: "102.2456875",
    accent: "emerald",
  },
  {
    state: "Kelantan",
    kind: "hospital",
    name: "Hospital Universiti Sains Malaysia",
    slug: "hospital-universiti-sains-malaysia-kelantan",
    address: "Jalan Raja Perempuan Zainab II, 16150 Kubang Kerian, Kelantan",
    latitude: "6.0996459",
    longitude: "102.2804832",
    accent: "blue",
  },
  {
    state: "Kelantan",
    kind: "clinic",
    name: "Klinik Kesihatan Bandar Kota Bharu",
    slug: "klinik-kesihatan-bandar-kota-bharu-kelantan",
    address: "Jalan Hospital, 15000 Kota Bharu, Kelantan",
    latitude: "6.1255186",
    longitude: "102.2429127",
    accent: "violet",
  },
  {
    state: "Kelantan",
    kind: "clinic",
    name: "Klinik Kesihatan Kubang Kerian",
    slug: "klinik-kesihatan-kubang-kerian-kelantan",
    address: "Jalan Pasir Puteh, 16150 Kubang Kerian, Kelantan",
    latitude: "6.0915062",
    longitude: "102.2722822",
    accent: "amber",
  },

  // Melaka
  {
    state: "Melaka",
    kind: "hospital",
    name: "Hospital Melaka",
    slug: "hospital-melaka",
    address: "Jalan Mufti Haji Khalil, 75400 Melaka",
    latitude: "2.2187528",
    longitude: "102.2616417",
    accent: "emerald",
  },
  {
    state: "Melaka",
    kind: "hospital",
    name: "Mahkota Medical Centre",
    slug: "mahkota-medical-centre-melaka",
    address: "No. 3, Mahkota Melaka, Jalan Merdeka, 75000 Melaka",
    latitude: "2.1876716",
    longitude: "102.2516082",
    accent: "blue",
  },
  {
    state: "Melaka",
    kind: "clinic",
    name: "Klinik Kesihatan Peringgit",
    slug: "klinik-kesihatan-peringgit-melaka",
    address: "Jalan Bukit Peringgit, 75400 Melaka",
    latitude: "2.2223254",
    longitude: "102.2544566",
    accent: "violet",
  },
  {
    state: "Melaka",
    kind: "clinic",
    name: "Klinik Kesihatan Ayer Keroh",
    slug: "klinik-kesihatan-ayer-keroh-melaka",
    address: "Ayer Keroh, 75450 Melaka",
    latitude: "2.2664055",
    longitude: "102.2845775",
    accent: "amber",
  },

  // Negeri Sembilan
  {
    state: "Negeri Sembilan",
    kind: "hospital",
    name: "Hospital Tuanku Ja'afar",
    slug: "hospital-tuanku-jaafar-negeri-sembilan",
    address: "Jalan Rasah, 70300 Seremban, Negeri Sembilan",
    latitude: "2.7091896",
    longitude: "101.9439604",
    accent: "emerald",
  },
  {
    state: "Negeri Sembilan",
    kind: "hospital",
    name: "Aurelius Hospital Negeri Sembilan",
    slug: "aurelius-hospital-negeri-sembilan",
    address: "Jalan BBN 2/1, Bandar Baru Nilai, 71800 Nilai, Negeri Sembilan",
    latitude: "2.8117570",
    longitude: "101.7735550",
    accent: "blue",
  },
  {
    state: "Negeri Sembilan",
    kind: "clinic",
    name: "Klinik Kesihatan Seremban",
    slug: "klinik-kesihatan-seremban-negeri-sembilan",
    address: "Jalan Rasah, 70300 Seremban, Negeri Sembilan",
    latitude: "2.7085102",
    longitude: "101.9401171",
    accent: "violet",
  },
  {
    state: "Negeri Sembilan",
    kind: "clinic",
    name: "Klinik Kesihatan Ampangan",
    slug: "klinik-kesihatan-ampangan-negeri-sembilan",
    address: "Jalan Kuala Pilah, Ampangan, 70400 Seremban, Negeri Sembilan",
    latitude: "2.7237356",
    longitude: "101.9876991",
    accent: "amber",
  },

  // Pahang
  {
    state: "Pahang",
    kind: "hospital",
    name: "Hospital Tengku Ampuan Afzan",
    slug: "hospital-tengku-ampuan-afzan-pahang",
    address: "Jalan Tanah Putih, 25100 Kuantan, Pahang",
    latitude: "3.8005722",
    longitude: "103.3212384",
    accent: "emerald",
  },
  {
    state: "Pahang",
    kind: "hospital",
    name: "Hospital Sultan Haji Ahmad Shah",
    slug: "hospital-sultan-haji-ahmad-shah-pahang",
    address: "Jalan Maran, 28000 Temerloh, Pahang",
    latitude: "3.4526383",
    longitude: "102.4532079",
    accent: "blue",
  },
  {
    state: "Pahang",
    kind: "clinic",
    name: "Klinik Kesihatan Bandar Kuantan",
    slug: "klinik-kesihatan-bandar-kuantan-pahang",
    address: "Jalan Gambut, 25000 Kuantan, Pahang",
    latitude: "3.8078000",
    longitude: "103.3260000",
    accent: "violet",
  },
  {
    state: "Pahang",
    kind: "clinic",
    name: "Klinik Kesihatan Temerloh",
    slug: "klinik-kesihatan-temerloh-pahang",
    address: "Jalan Ahmad Shah, 28000 Temerloh, Pahang",
    latitude: "3.4460224",
    longitude: "102.4236346",
    accent: "amber",
  },

  // Penang
  {
    state: "Penang",
    kind: "hospital",
    name: "Hospital Pulau Pinang",
    slug: "hospital-pulau-pinang",
    address: "Jalan Residensi, 10990 George Town, Penang",
    latitude: "5.4170320",
    longitude: "100.3114869",
    accent: "emerald",
  },
  {
    state: "Penang",
    kind: "hospital",
    name: "Island Hospital",
    slug: "island-hospital-penang",
    address: "308, Macalister Road, 10450 George Town, Penang",
    latitude: "5.4251000",
    longitude: "100.3123000",
    accent: "blue",
  },
  {
    state: "Penang",
    kind: "clinic",
    name: "Klinik Kesihatan Jalan Perak",
    slug: "klinik-kesihatan-jalan-perak-penang",
    address: "Jalan Perak, 11600 George Town, Penang",
    latitude: "5.4021586",
    longitude: "100.3148686",
    accent: "violet",
  },
  {
    state: "Penang",
    kind: "clinic",
    name: "Klinik Kesihatan Bayan Baru",
    slug: "klinik-kesihatan-bayan-baru-penang",
    address: "Jalan Tengah, Bayan Baru, 11900 Bayan Lepas, Penang",
    latitude: "5.3202892",
    longitude: "100.2797613",
    accent: "amber",
  },

  // Perak
  {
    state: "Perak",
    kind: "hospital",
    name: "Hospital Raja Permaisuri Bainun",
    slug: "hospital-raja-permaisuri-bainun-perak",
    address: "Jalan Raja Ashman Shah, 30450 Ipoh, Perak",
    latitude: "4.6025921",
    longitude: "101.0890924",
    accent: "emerald",
  },
  {
    state: "Perak",
    kind: "hospital",
    name: "KPJ Ipoh Specialist Hospital",
    slug: "kpj-ipoh-specialist-hospital-perak",
    address: "26, Jalan Raja Dihilir, 30350 Ipoh, Perak",
    latitude: "4.5949619",
    longitude: "101.0961546",
    accent: "blue",
  },
  {
    state: "Perak",
    kind: "clinic",
    name: "Klinik Kesihatan Greentown",
    slug: "klinik-kesihatan-greentown-perak",
    address: "Jalan Raja Musa Aziz, 30450 Ipoh, Perak",
    latitude: "4.6025075",
    longitude: "101.0871166",
    accent: "violet",
  },
  {
    state: "Perak",
    kind: "clinic",
    name: "Klinik Kesihatan Gunung Rapat",
    slug: "klinik-kesihatan-gunung-rapat-perak",
    address: "Jalan Raja Dr. Nazrin Shah, 31350 Ipoh, Perak",
    latitude: "4.5627052",
    longitude: "101.1120769",
    accent: "amber",
  },

  // Perlis
  {
    state: "Perlis",
    kind: "hospital",
    name: "Hospital Tuanku Fauziah",
    slug: "hospital-tuanku-fauziah-perlis",
    address: "3, Jalan Tun Abdul Razak, Pusat Bandar Kangar, 01000 Kangar, Perlis",
    latitude: "6.4415602",
    longitude: "100.1903474",
    accent: "emerald",
  },
  {
    state: "Perlis",
    kind: "hospital",
    name: "KPJ Perlis Specialist Hospital",
    slug: "kpj-perlis-specialist-hospital",
    address: "Jalan Dato Wan Ahmad, 01000 Kangar, Perlis",
    latitude: "6.4333123",
    longitude: "100.1863368",
    accent: "blue",
  },
  {
    state: "Perlis",
    kind: "clinic",
    name: "Klinik Kesihatan Kangar",
    slug: "klinik-kesihatan-kangar-perlis",
    address: "Jalan Kolam, 01000 Kangar, Perlis",
    latitude: "6.4398406",
    longitude: "100.1904707",
    accent: "violet",
  },
  {
    state: "Perlis",
    kind: "clinic",
    name: "Klinik Kesihatan Arau",
    slug: "klinik-kesihatan-arau-perlis",
    address: "Jalan Pauh, 02600 Arau, Perlis",
    latitude: "6.4297000",
    longitude: "100.2693000",
    accent: "amber",
  },

  // Sabah
  {
    state: "Sabah",
    kind: "hospital",
    name: "Queen Elizabeth Hospital",
    slug: "queen-elizabeth-hospital-sabah",
    address: "13A, Jalan Penampang, 88200 Kota Kinabalu, Sabah",
    latitude: "5.9565521",
    longitude: "116.0732720",
    accent: "emerald",
  },
  {
    state: "Sabah",
    kind: "hospital",
    name: "KPJ Sabah Specialist Hospital",
    slug: "kpj-sabah-specialist-hospital",
    address: "Off Jalan Damai, 88300 Kota Kinabalu, Sabah",
    latitude: "5.9670490",
    longitude: "116.0929883",
    accent: "blue",
  },
  {
    state: "Sabah",
    kind: "clinic",
    name: "Klinik Kesihatan Luyang",
    slug: "klinik-kesihatan-luyang-sabah",
    address: "Jalan Kolam, Luyang, 88300 Kota Kinabalu, Sabah",
    latitude: "5.9463133",
    longitude: "116.0910378",
    accent: "violet",
  },
  {
    state: "Sabah",
    kind: "clinic",
    name: "Klinik Kesihatan Inanam",
    slug: "klinik-kesihatan-inanam-sabah",
    address: "Jalan Tuaran, Inanam, 88450 Kota Kinabalu, Sabah",
    latitude: "5.9955000",
    longitude: "116.1320000",
    accent: "amber",
  },

  // Sarawak
  {
    state: "Sarawak",
    kind: "hospital",
    name: "Hospital Umum Sarawak",
    slug: "hospital-umum-sarawak",
    address: "Jalan Hospital, 93586 Kuching, Sarawak",
    latitude: "1.5430052",
    longitude: "110.3396604",
    accent: "emerald",
  },
  {
    state: "Sarawak",
    kind: "hospital",
    name: "Normah Medical Specialist Centre",
    slug: "normah-medical-specialist-centre-sarawak",
    address: "Jalan Tun Abdul Rahman Yaakub, Petra Jaya, 93050 Kuching, Sarawak",
    latitude: "1.5781614",
    longitude: "110.3287874",
    accent: "blue",
  },
  {
    state: "Sarawak",
    kind: "clinic",
    name: "Klinik Kesihatan Jalan Masjid",
    slug: "klinik-kesihatan-jalan-masjid-sarawak",
    address: "Jalan Masjid, 93400 Kuching, Sarawak",
    latitude: "1.5570874",
    longitude: "110.3427623",
    accent: "violet",
  },
  {
    state: "Sarawak",
    kind: "clinic",
    name: "Klinik Kesihatan Petra Jaya",
    slug: "klinik-kesihatan-petra-jaya-sarawak",
    address: "Jalan Siol Kanan, Petra Jaya, 93050 Kuching, Sarawak",
    latitude: "1.5910765",
    longitude: "110.3396981",
    accent: "amber",
  },

  // Selangor
  {
    state: "Selangor",
    kind: "hospital",
    name: "Sunway Medical Centre",
    slug: "sunway-medical-centre-selangor",
    address: "No. 5, Jalan Lagoon Selatan, Bandar Sunway, 47500 Subang Jaya, Selangor",
    latitude: "3.0661113",
    longitude: "101.6085546",
    accent: "emerald",
  },
  {
    state: "Selangor",
    kind: "hospital",
    name: "Subang Jaya Medical Centre",
    slug: "subang-jaya-medical-centre-selangor",
    address: "No. 1, Jalan SS 12/1A, 47500 Subang Jaya, Selangor",
    latitude: "3.0790791",
    longitude: "101.5936654",
    accent: "blue",
  },
  {
    state: "Selangor",
    kind: "clinic",
    name: "Klinik Kesihatan Seksyen 7 Shah Alam",
    slug: "klinik-kesihatan-seksyen-7-shah-alam-selangor",
    address: "Persiaran Kayangan, Seksyen 7, 40000 Shah Alam, Selangor",
    latitude: "3.0723940",
    longitude: "101.4909955",
    accent: "violet",
  },
  {
    state: "Selangor",
    kind: "clinic",
    name: "Klinik Kesihatan Kelana Jaya",
    slug: "klinik-kesihatan-kelana-jaya-selangor",
    address: "Jalan SS 6/3A, Kelana Jaya, 47301 Petaling Jaya, Selangor",
    latitude: "3.0989938",
    longitude: "101.6006615",
    accent: "amber",
  },

  // Terengganu
  {
    state: "Terengganu",
    kind: "hospital",
    name: "Hospital Sultanah Nur Zahirah",
    slug: "hospital-sultanah-nur-zahirah-terengganu",
    address: "Jalan Sultan Mahmud, 20400 Kuala Terengganu, Terengganu",
    latitude: "5.3264680",
    longitude: "103.1505428",
    accent: "emerald",
  },
  {
    state: "Terengganu",
    kind: "hospital",
    name: "KMI Kuala Terengganu Medical Centre",
    slug: "kmi-kuala-terengganu-medical-centre",
    address: "Lot 3963, Jalan Sultan Mahmud, 20400 Kuala Terengganu, Terengganu",
    latitude: "5.3139123",
    longitude: "103.1560252",
    accent: "blue",
  },
  {
    state: "Terengganu",
    kind: "clinic",
    name: "Klinik Kesihatan Hiliran",
    slug: "klinik-kesihatan-hiliran-terengganu",
    address: "Jalan Hiliran, 20300 Kuala Terengganu, Terengganu",
    latitude: "5.3137337",
    longitude: "103.1346990",
    accent: "violet",
  },
  {
    state: "Terengganu",
    kind: "clinic",
    name: "Klinik Kesihatan Chendering",
    slug: "klinik-kesihatan-chendering-terengganu",
    address: "Jalan Kubang Ikan, Chendering, 21080 Kuala Terengganu, Terengganu",
    latitude: "5.2650000",
    longitude: "103.1830000",
    accent: "amber",
  },
];
